config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # get 'persons/profile', as: 'user_root'
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :tickets, only: [:new, :create, :show, :index]
  resource :search, only: [:new, :show, :edit]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations
    resources :routes do
      patch :del_station, on: :member
      patch :add_station, on: :member
      patch :add_train, on: :member
    end
    resources :tickets
    get 'welcome/index'
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :trains, dependent: :nullify, foreign_key: 'current_station_id', inverse_of: :current_station
  has_many :railway_stations_routes, dependent: :destroy
  has_many :routes, through: :railway_stations_routes
end

app/controllers/admin/railway_stations_controller.rb
module Admin
  class RailwayStationsController < Admin::BaseController
    before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

    def index
      @railway_stations = RailwayStation.all
    end

    def show; end

    def new
      @railway_station = RailwayStation.new
    end

    def edit; end

    def create
      @railway_station = RailwayStation.new(railway_station_params)

      respond_to do |format|
        if @railway_station.save
          format.html { redirect_to [:admin, @railway_station], notice: 'Railway station was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @railway_station.update(railway_station_params)
          format.html { redirect_to [:admin, @railway_station], notice: 'Railway station was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @railway_station.destroy
      respond_to do |format|
        format.html { redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      end
    end

    private

    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
  end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.erb
<%= form_with(model: [:admin, railway_station],  local: true ) do |form| %>
  <%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit t('.submit', action: @railway_station.new_record? ? 'Создать' : 'Редактировать')%>
  </div>
<% end %>

app/views/admin/railway_stations/_railway_station.html.erb
<p>
  <%= link_to railway_station.title, [:admin, railway_station] %> -
  <%= link_to t('common.edit'), edit_admin_railway_station_path(railway_station) %> -
  <%= link_to t('common.delete'), [:admin, railway_station], method: :delete, data: { confirm: 'Вы действительно хотите удалить?' } %>
</p>

app/views/admin/railway_stations/edit.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('common.info'), [:admin, @railway_station] %> |
<%= link_to t('common.back'), admin_railway_stations_path %>

app/views/admin/railway_stations/index.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<%= render partial: "railway_station", collection: @railway_stations %>

<br/>

<%= link_to t('.create'), new_admin_railway_station_path %>

app/views/admin/railway_stations/new.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('common.back'), admin_railway_stations_path %>

app/views/admin/railway_stations/show.html.erb
<p>
  <div class = 'edit_form_del visibility'>
    <strong><%= t('.title') %></strong>
    <%= @railway_station.title %>
  </div>
  <div class = 'edit_form_add invisibility'>
    <%= render 'form', railway_station: @railway_station %>
  </div>
</p>

<p>
  <strong><%= t('.train') %></strong>
  <%= @railway_station.trains.map(&:name) if @railway_station.trains.any? %>
  <%= t('.not_train') if !@railway_station.trains.any? %>
</p>

<p>
  <strong><%= t('.route') %></strong>
  <%= @railway_station.routes.map(&:name) if @railway_station.routes.any? %>
  <%= t('.not_route') if !@railway_station.routes.any? %>
</p>


<div class = 'edit_form_del visibility'>
  <%= link_to t('common.change'), '', class: "edit_button_first" %>
</div>
<div class = 'edit_form_add invisibility'>
  <%= link_to t('common.cancel'), '', class: "edit_button_last" %>
</div>

<%= link_to t('common.back'), admin_railway_stations_path %>