config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # get 'persons/profile', as: 'user_root'
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :tickets, only: [:new, :create, :show, :index]
  resource :search, only: [:new, :show, :edit]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations
    resources :routes do
      patch :del_station, on: :member
      patch :add_station, on: :member
      patch :add_train, on: :member
    end
    resources :tickets
    get 'welcome/index'
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  validates :name, uniqueness: true

  has_one :train, dependent: :nullify

  has_many :railway_stations_routes, dependent: :destroy
  has_many :railway_stations, -> { order('position') }, through: :railway_stations_routes
end

app/controllers/admin/routes_controller.rb
module Admin
  class RoutesController < Admin::BaseController
    before_action :set_route, only: [:show, :edit, :update, :destroy, :del_station, :add_station, :add_train]

    def index
      @routes = Route.all
    end

    def show; end

    def new
      @route = Route.new
    end

    def edit; end

    def create
      ActiveRecord::Base.transaction do
        @route = Route.new(name: 'name')
        if @route.save
          redirect_to [:admin, @route], notice: 'Route was successfully created.'
        else
          render :new
        end
        stations_add_route
      end
    end

    def update
      timetable_params
      if route_update
        redirect_to admin_routes_url, notice: 'Route was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @route.destroy
      redirect_to admin_routes_path
    end

    def add_station
      @add_station = update_params[:add_station_id]
      @route.railway_stations_routes
            .create!(railway_station_id: @add_station, position: @route.railway_stations_routes.size)
      redirect_to edit_admin_route_path
    end

    def del_station
      @del_station = update_params[:del_station_id]
      @route.railway_stations_routes.find_by(railway_station_id: @del_station).delete
      redirect_to edit_admin_route_path
    end

    def add_train
      @add_train = update_params[:add_train_id]
      Train.find(@add_train).update(route_id: @route.id)
      redirect_to edit_admin_route_path
    end

    private

    def stations_add_route
      @route_stations = route_params[:railway_stations_ids].reject(&:blank?)
      @route_stations.each_with_index do |station, position|
        @route.railway_stations_routes.create!(railway_station_id: station, route_id: @route.id, position: position)
      end
    end

    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(:name, railway_stations_ids: [])
    end

    def timetable_params
      params.require(:route).permit(:name, :id, :add_station_id, :del_station_id, railway_stations_route: {})
    end

    def update_params
      params.permit(:id, :add_station_id, :del_station_id, :add_train_id)
    end

    def route_update
      @route.update(name: timetable_params[:name])
      unless timetable_params[:railway_stations_route].nil?
        timetable_params[:railway_stations_route].each do |rsr|
          RailwayStationsRoute.find(rsr[0]).update(rsr[1])
        end
      end
    end
  end
end

app/views/admin/routes/_route.html.erb
<div>
  <div class = 'col-md-6'>
    <div class = 'edit_form_del visibility'>
      <%= link_to route.name, [:admin, route], class: 'form form-control text-center' %>
    </div>

    <%= form_with(model: [:admin, route], local: true) do |form| %>
      <div class="edit_form_add invisibility col-md-8">
        <%= form.text_field :name, class: 'form form-control text-center' %>
      </div>
      <div class="edit_form_add invisibility col-md-4">
        <%= form.submit 'Сохранить', class: 'form form-control text-center btn btn-success' %>
      </div>
    <% end %>

  </div>

  <div class = 'col-md-2 edit_form_del visibility'>
    <%= link_to t('common.change'), '', class: 'edit_button_first form form-control text-center btn btn-success' %>
  </div>
  <div class = 'col-md-2 edit_form_add invisibility'>
    <%= link_to t('common.cancel'), '', class: 'edit_button_second form form-control text-center btn btn-success' %>
  </div>

  <div class = 'col-md-2'>
    <%= link_to t('common.edit'), edit_admin_route_path(route), class: 'form form-control text-center' %>
  </div>

  <div class = 'col-md-2'>
    <%= link_to t('common.delete'), [:admin, route], method: :delete,
      data: { confirm: 'Вы действительно хотите удалить?' }, class: 'form form-control text-center' %>
  </div>
</div>

app/views/admin/routes/edit.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<%= form_with model: [:admin, @route] do |route_form| %>
  <div class="form-group">
      <strong><%= t('.name_route') %></strong>
      <%= route_form.text_field :name, class: "form-control" %>
      <%= route_form.hidden_field :id %>
  </div>

  <br/>
  <strong><%= t('.stations') %></strong>
  <div class="form-group form-group-sm">
    <table class="table">
      <thead>
        <tr class="success">
          <td class="col-md-4 text-center"><%= t('.name_station') %></td>
          <td class="col-md-2 text-center"><%= t('.position') %></td>
          <td class="col-md-3 text-center"><%= t('.arrival') %></td>
          <td class="col-md-3 text-center"><%= t('.departure') %></td>
        </tr>
      </thead>

      <tbody>
      <% @route.railway_stations_routes.each do |rsr| %>
        <%= route_form.fields_for rsr, index: rsr.id do |rsr_form| %>
          <tr>
            <% station = rsr.railway_station %>
            <td class="col-md-4 text-center"><%= station.title %></td>
            <td class="col-md-2">
              <%= rsr_form.number_field(:position, options = {in: 0..@route.railway_stations_routes.size,
                                        class: "form form-control text-center"}) %>
            </td>
            <td class="col-md-3">
              <%= rsr_form.time_field(:arrival, value: rsr.departure.try(:strftime, "%H:%M"),
                                        class: "form form-control text-center") %>
            </td>
            <td class="col-md-3">
              <%= rsr_form.time_field(:departure, value: rsr.departure.try(:strftime, "%H:%M"),
                                        class: "form form-control text-center") %>
            </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="actions">
    <%= route_form.submit t('common.submit.update'), class: "btn btn-primary form-control" %>
  </div>
<% end %>

<br/>
<%= form_with(url: add_station_admin_route_path, method: :patch) do |route_form| %>
  <div class="field">
    <table class="table">
        <tr>
          <td class="col-md-4 text-center"><strong><%= t('.add_station') %></strong></td>
          <td class="col-md-4"><%= route_form.select(:add_station_id,
                                (RailwayStation.all-@route.railway_stations).collect { |s| [ s.title, s.id ] },
                                { include_blank: true}, class: "form form-control") %></td>
          <td class="col-md-4 text-center">
            <%= route_form.submit t('.submit.add'), class: "btn btn-primary form-control" %>
          </td>
      </tr>
    </table>
  </div>
<% end %>

<br/>
<%= form_with(url: del_station_admin_route_path, method: :patch) do |route_form| %>
  <div class="field">
    <table class="table">
        <tr>
          <td class="col-md-4 text-center"><strong><%= t('.del_station') %></strong></td>
          <td class="col-md-4"><%= route_form.select(:del_station_id, @route.railway_stations.collect { |s| [ s.title, s.id ] },
                          { include_blank: true }, class: "form form-control") %></td>
          <td class="col-md-4 text-center">
            <%= route_form.submit t('.submit.delete'), class: "btn btn-primary form-control" %>
          </td>
      </tr>
    </table>
  </div>
<% end %>

<br/>
<strong class="col-md-12 text-center" style="background-color: rgb(223, 240, 216); min-height:38px; padding-top:10px">
  <% if @route.train.nil? %>
    <%= t('.not_train') %>
  <% else %>
    <%= t('.train_in') %>
    <%= @route.train.name %>
  <% end %>
</strong>

<br/>
<%= form_with(url: add_train_admin_route_path, method: :patch) do |route_form| %>
  <div class="field">
    <table class="table">
        <tr>
          <td class="col-md-4 text-center"><strong><%= t('.add_train') %></strong></td>
          <td class="col-md-4"><%= route_form.select(:add_train_id, Train.all.collect { |t| [ t.name, t.id ] },
                                                     { include_blank: true }, class: "form form-control") %></td>
          <td class="col-md-4 text-center">
            <%= route_form.submit t('.submit.train'), class: "btn btn-primary form-control" %>
          </td>
      </tr>
    </table>
  </div>
<% end %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/index.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<%= render partial: "route", collection: @routes %>

<br/>

<%= link_to t('.create'), new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<%= form_with(model: [:admin, @route], local: true) do |form| %>
  <%= render 'common/errors', resource: @route %>

  <div class="form-group">
    <%= form.label :railway_stations %>
    <%= form.select(:railway_stations_ids, RailwayStation.all.collect { |s| [ s.title, s.id ] }, { :prompt => false },
                    { :multiple => true, :size => 7, class: "form-control"}) %>
  </div>

  <div class="actions">
    <%= form.submit t('common.submit.create'), class: "btn btn-primary form-control" %>
  </div>
<% end %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/show.html.erb
<p>
  <strong><%= t('.title') %></strong>
  <%= @route.name %>
</p>

<p>
  <strong><%= t('.train') %></strong>
  <%= @route.train.name if !@route.train.nil? %>
  <%= t('.not_train') if @route.train.nil? %>
</p>

<p>
  <strong><%= t('.station') %></strong>
  <%= @route.railway_stations.map(&:title) if @route.railway_stations.any? %>
  <%= t('.not_station') if !@route.railway_stations.any? %>
</p>

<%= link_to t('common.edit'), edit_admin_route_path(@route) %> |
<%= link_to t('common.back'), admin_routes_path %>