config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # get 'persons/profile', as: 'user_root'
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :tickets, only: [:new, :create, :show, :index]
  resource :search, only: [:new, :show, :edit]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations
    resources :routes do
      patch :del_station, on: :member
      patch :add_station, on: :member
      patch :add_train, on: :member
    end
    resources :tickets
    get 'welcome/index'
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  validates :number, presence: true
  validates :train_id, presence: true
  validates :type, inclusion: { in: %w[VipCarriage EconomCarriage CoupeCarriage ExpressCarriage],
                                message: "%{value} is not a valid type" }

  belongs_to :train
  before_validation :set_number

  scope :express, -> { where(type: 'ExpressCarriage') }
  scope :econom, -> { where(type: 'EconomCarriage') }
  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :vip, -> { where(type: 'VipCarriage') }

  private

  def set_number
    self.number ||= train.carriages.size + 1
  end
end

app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
  validates :place_top, :place_botton, presence: true
end

app/models/econom_carriage.rb
class EconomCarriage < Carriage
  validates :place_top, :place_botton, :place_top_side, :place_botton_side, presence: true
end

app/models/express_carriage.rb
class ExpressCarriage < Carriage
  validates :seat, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :trains, dependent: :nullify, foreign_key: 'current_station_id', inverse_of: :current_station
  has_many :railway_stations_routes, dependent: :destroy
  has_many :routes, through: :railway_stations_routes
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  validates :railway_station_id, uniqueness: { scope: :route_id }

  belongs_to :railway_station
  belongs_to :route

  has_many :tickets, dependent: :destroy

  after_create :set_name

  private

  def set_name
    route_name = "#{route.railway_stations.first.title} - #{route.railway_stations.last.title}"
    route.update(name: route_name)
  end
end

app/models/route.rb
class Route < ApplicationRecord
  validates :name, uniqueness: true

  has_one :train, dependent: :nullify

  has_many :railway_stations_routes, dependent: :destroy
  has_many :railway_stations, -> { order('position') }, through: :railway_stations_routes
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :passport_series, presence: true
  validates :passport_numbers, presence: true
  validates_with TicketByTrainValidator

  belongs_to :user
  belongs_to :rsr_first, class_name: 'RailwayStationsRoute', foreign_key: :rsr_first_id, inverse_of: :tickets
  belongs_to :rsr_last, class_name: 'RailwayStationsRoute', foreign_key: :rsr_last_id, inverse_of: :tickets

  def route_name
    "#{rsr_first.railway_station.title} - #{rsr_last.railway_station.title} "
  end
end

app/models/train.rb
class Train < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, inverse_of: :trains
  belongs_to :route, class_name: 'Route', foreign_key: :route_id, inverse_of: :train

  has_many :carriages, dependent: :destroy

  def place(type, place)
    carriages.where(type: type).sum(place.to_sym)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true

  has_many :tickets, dependent: :destroy
end

app/models/vip_carriage.rb
class VipCarriage < Carriage
  validates :place_botton, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    current_user.admin? ? admin_welcome_index_path : new_search_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  def show
    search_route
    @station_first = RailwayStation.find(params[:station_first_id])
    @station_last = RailwayStation.find(params[:station_last_id])
  end

  def new
    @stations = RailwayStation.all
  end

  def edit; end

  def create; end

  def search_route
    @search_rsr = SearchRouteService.search(params[:station_first_id], params[:station_last_id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :destroy]

  def index
    return @tickets = Ticket.all if current_user.admin?

    @tickets = current_user.tickets
  end

  def show
    info = ticket_info
    @qr = QrCodeService.generate_qr(info, @ticket)
    info
  end

  def new
    @ticket = Ticket.new
  end

  def edit; end

  def create
    user_id = { user_id: current_user[:id] }
    @ticket = Ticket.new(train_params.merge(ticket_params).merge(user_id))
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'ticket was successfully created.' }
      else
        format.html { render :new }
      end
    end
    SendService.send_notification(current_user, @ticket)
  end

  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'ticket was successfully destroyed.' }
    end
    SendService.send_destroy_ticket(current_user, @ticket)
  end

  protected

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  private

  def ticket_params
    params.require(:ticket).permit(:last_name, :first_name, :father_name, :passport_series, :passport_numbers)
  end

  def train_params
    first_station = RailwayStationsRoute.find(params[:ticket_rsr_first])
    last_station = RailwayStationsRoute.find(params[:ticket_rsr_last])
    { rsr_first_id: first_station.id, rsr_last_id: last_station.id }
  end

  def ticket_info
    train = @ticket.rsr_first.route.train
    station_first = @ticket.rsr_first.railway_station
    station_last = @ticket.rsr_last.railway_station
    time_first = @ticket.rsr_first.departure
    time_last = @ticket.rsr_last.arrival
    @ticket_info = { train: train.name, station_first: station_first.title, station_last: station_last.title,
                     time_first: time_first, time_last: time_last }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/searches/new.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<%= form_with(url: search_path, local: true,  method: :get, class: 'search_form') do |form| %>
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-xs-6 col-md-4 control-label">
        <%= form.label :station_first_id, t('tickets.common.station_first') %>
      </label>
      <div class="col-xs-12 col-sm-6 col-md-8">
        <%= form.select(:station_first_id, @stations.map { |s| [ s.title, s.id ] } ) %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-xs-6 col-md-4 control-label">
        <%= form.label :station_last_id, t('tickets.common.station_last') %>
      </label>
      <div class="col-xs-12 col-sm-6 col-md-8">
        <%= form.select(:station_last_id, @stations.map { |s| [ s.title, s.id ] } ) %>
      </div>
    </div>

    <div class="form-group">
      <%= form.submit t('.search'), class: "btn btn-info btn-block find"%>
    </div>
  </form>
<% end %>

app/views/searches/show.html.erb
<h2><span class="label label-success"><%= t('.title') %></span></h2>

<% if @search_rsr.empty? %>
  <%= t('.not_train') %>
<% else %>
  <table>
    <thead>
    <tr>
      <td><%= t('.route') %></td>
      <td><%= t('tickets.common.station_first') %></td>
      <td><%= t('tickets.common.station_first_departure') %></td>
      <td><%= t('tickets.common.station_last') %></td>
      <td><%= t('tickets.common.station_last_arrival') %></td>
      <td><%= t('.ticket_buy') %></td>
    </tr>
    </thead>
    <tbody>
    <% @search_rsr.each do |search_rsr| %>
      <tr>
        <td><%= search_rsr[:route].name %></td>
        <td><%= @station_first.title %></td>
        <td><%= search_rsr[:firstrsr].departure.try(:strftime, "%H:%M") %></td>
        <td><%= @station_last.title %></td>
        <td><%= search_rsr[:lastrsr].arrival.try(:strftime, "%H:%M") %></td>
        <td>
        <%= form_tag new_ticket_path(@search), method: :get do %>
          <% rsr_first = search_rsr[:firstrsr].id %>
          <% rsr_last = search_rsr[:lastrsr].id %>
          <%= hidden_field_tag :ticket_rsr_first, rsr_first %>
          <%= hidden_field_tag :ticket_rsr_last, rsr_last %>
          <%= submit_tag t('.ticket_buy') %>
        <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


<p class="navbar-text navbar-right"><a href="#" class="navbar-link"><%= link_to t('.new_search'), new_search_path(@search) %></a></p>