config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # get 'persons/profile', as: 'user_root'
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :tickets, only: [:new, :create, :show, :index]
  resource :search, only: [:new, :show, :edit]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations
    resources :routes do
      patch :del_station, on: :member
      patch :add_station, on: :member
      patch :add_train, on: :member
    end
    resources :tickets
    get 'welcome/index'
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, inverse_of: :trains
  belongs_to :route, class_name: 'Route', foreign_key: :route_id, inverse_of: :train

  has_many :carriages, dependent: :destroy

  def place(type, place)
    carriages.where(type: type).sum(place.to_sym)
  end
end

app/controllers/admin/trains_controller.rb
module Admin
  class TrainsController < Admin::BaseController
    before_action :set_train, only: [:show, :edit, :update, :destroy]

    def index
      @trains = Train.all
    end

    def show; end

    def new
      @train = Train.new
    end

    def edit; end

    def create
      @train = Train.new(train_params)
      respond_to do |format|
        if @train.save
          format.html { redirect_to [:admin, @train], notice: 'Train was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @train.update(train_params)
          format.html { redirect_to admin_trains_url, notice: 'Train was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @train.destroy
      respond_to do |format|
        format.html { redirect_to admin_trains_url, notice: 'Train was successfully destroyed.' }
      end
    end

    private

    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:name, :current_station_id, :route_id, :sortcar)
    end
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_with(model: [:admin, train], local: true) do |form| %>
  <%= render 'common/errors', resource: train %>

  <div class="form form-control">
    <%= form.label :name, "Номер поезда", class: 'text-center col-md-4' %>
    <%= form.number_field :name, class: 'text-center col-md-8' %>
  </div>

  <div class="form form-control">
    <%= form.label :current_station, "Текущая станция", class: 'text-center col-md-4'  %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="form form-control">
    <%= form.label :route, "Маршрут", class: 'text-center col-md-4'  %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="form form-control">
    <p class='text-center col-md-8'>Сортировка вагонов с головы поезда</p>
    <%= form.check_box :sortcar, class: 'text-center col-md-4' %>
  </div>

  <div>
    <%= form.submit t('common.submit.update'), class: 'form form-control btn btn-success col-md-4 text-center'  %>
  </div>
<% end %>

app/views/admin/trains/_thead.html.erb
        <div class="col-md-2 form text-center">"Номер поезда"</div>
        <div class="col-md-2 form text-center">"Текущая станция"</div>
        <div class="col-md-2 form text-center">"Маршрут"</div>
        <div class="col-md-3 form text-center">"Сортировка вагонов с головы поезда"</div>
        <div class="col-md-3 form text-center">"Действие"</div>

app/views/admin/trains/_train.html.erb
<%= form_with(model: [:admin, train], local: true)  do |form| %>
  <%= render 'common/errors', resource: train %>
  <div class="form-group form-group-sm">
    <table class="table">
      <tbody>
        <tr>
          <td class="col-md-3 text-center">
            <div class = 'edit_form_del visibility'>
              <%= form.label train.name, class: 'form form-control text-center' %>
            </div>
            <%= form_with(model: [:admin, train], local: true) do |form| %>
              <div class="edit_form_add invisibility">
                <%= form.number_field :name, class: 'form form-control text-center' %>
              </div>
              <div class="edit_form_add invisibility">
                <%= form.submit 'Сохранить', class: 'form form-control text-center btn btn-success' %>
              </div>
            <% end %>
          </td>

          <td class="col-md-2 text-center">
            <div>
              <%= train.current_station.title %>
            </div>
          </td>

          <td class="col-md-2 text-center">
            <div>
              <%= train.route.name %>
            </div>
          </td>

          <td class="col-md-2 text-center">
            <div>
              <%= train.sortcar %>
            </div>
          </td>

          <td class="col-md-1 text-center">
            <div class = 'edit_form_del visibility'>
              <%=  link_to t('common.change'), '', class: "edit_button_first form form-control text-center btn btn-success" %>
            </div>
            <div class="edit_form_add invisibility">
              <%=  link_to t('common.cancel'), '', class: "edit_button_second form form-control text-center btn btn-warning" %>
            </div>
          </td>

          <td class="col-md-1 text-center">
            <div>
              <%=  link_to t('common.edit'), edit_admin_train_path(train),
                class: "form form-control text-center btn btn-warning" %>
            </div>
          </td>

          <td class="col-md-1 text-center">
            <div>
              <%=  link_to t('common.delete'), [:admin, train], method: :delete,
                data: { confirm: 'Вы действительно хотите удалить?' },
                class: "form form-control text-center btn btn-danger"  %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/admin/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render "form", train: @train %>

<br/>

<%= link_to 'Посмотреть', [:admin, @train] %> |
<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Поезда</h1>

<%= render "thead" %>
<%= render partial: "train", collection: @trains %>

<br/>

<%= link_to 'Новый поезд', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong>Номер поезда:</strong>
  <%= @train.name %>
</p>

<p>
  <strong>Название маршрута:</strong>
  <%= @train.route.name %>
</p>

<p>
  <strong>Текущая станция:</strong>
  <%= @train.current_station.title %>
</p>

<p>
  <em>Количество сидячих вагонов:</em>
  <%= @train.carriages.group(:type).count['ExpressCarriage'] ||= 0 %>
</p>

<p>
  <em>Количество плацкартных вагонов:</em>
  <%= @train.carriages.group(:type).count['EconomCarriage'] ||= 0 %>
</p>

<p>
  <em>Количество купейных вагонов:</em>
  <%= @train.carriages.group(:type).count['CoupeCarriage'] ||= 0 %>
</p>

<p>
  <em>Количество люкс вагонов:</em>
  <%= @train.carriages.group(:type).count['VipCarriage'] ||= 0 %>
</p>

<strong>Вагоны в составе поезда:</strong>
<% car = @train.carriages.reverse %>
<% car = @train.carriages if @train.sortcar %>
<% car.each do |carriage| %>
  <%= render :partial => 'admin/carriages/carriage', :locals => {:carriage => carriage} %>
<% end %>

<p>
<%= link_to 'Добавить вагон', new_admin_train_carriage_path(@train) %>
</p>
<%= link_to 'Редактировать поезд', edit_admin_train_path(@train) %> |
<%= link_to 'Назад к списку поездов', admin_trains_path %>